// <auto-generated />
namespace WebOnl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Update1108 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update1108));
        
        string IMigrationMetadata.Id
        {
            get { return "202308110751229_Update1108"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
